import { TetuGame } from './TetuGame';

export function getMonsterName(monsterId: number): string {
  const name = MONSTER_NAMES.get(monsterId);
  if (!name) {
    console.log(`No name found for ${monsterId}`);
    return 'Unknown';
  }
  return name;
}

export const MONSTER_NAMES = new Map<number, string>([
  [TetuGame.MONSTERS.REBELLIOUS_PEASANT_32, 'Rebellious Peasant'],
  [TetuGame.MONSTERS.REBELLIOUS_PEASANT_34, 'Rebellious Peasant'],
  [TetuGame.MONSTERS.TOUGH_DESERTER_32, 'Tough Deserter'],
  [TetuGame.MONSTERS.TOUGH_DESERTER_34, 'Tough Deserter'],
  [TetuGame.MONSTERS.BLOODTHIRSTY_MADMAN_32, 'Bloodthirsty Madman'],
  [TetuGame.MONSTERS.BLOODTHIRSTY_MADMAN_34, 'Bloodthirsty Madman'],
  [TetuGame.MONSTERS.FEROCIOUS_WOLFS_34, 'Ferocious Wolfs'],
  [TetuGame.MONSTERS.DRUNK_CROSSBOWMAN_32, 'Drunk Crossbowman'],
  [TetuGame.MONSTERS.DRUNK_CROSSBOWMAN_34, 'Drunk Crossbowman'],
  [TetuGame.MONSTERS.VILE_SERPENT_35, 'Vile Serpent'],
  [TetuGame.MONSTERS.THE_MAN_EATING_BEAR_35, 'The Man-Eating Bear'],
  [TetuGame.MONSTERS.BANDIT_CROWD_10, 'Bandit Crowd'],
  [TetuGame.MONSTERS.HANGMANS_PATROL_33, 'Hangmans Patrol'],
  [TetuGame.MONSTERS.MIDNIGHTER_2, 'Midnighter'],
  [TetuGame.MONSTERS.FOREST_CHORT_35, 'Forest Chort'],
  [TetuGame.MONSTERS.INFECTED_SPIRIT_OF_THE_FOREST_3, 'Infected Spirit of the Forest'],
  [TetuGame.MONSTERS.RESTLESS_SPIRIT_10, 'Restless Spirit'],
  [TetuGame.MONSTERS.MOCK1, 'MOCK1'],
  [TetuGame.MONSTERS.INFECTED_DEADMAN_JUNIOR_32, 'Infected Deadman'],
  [TetuGame.MONSTERS.INFECTED_DEADMAN_JUNIOR_34, 'Infected Deadman'],
  [TetuGame.MONSTERS.THRALL_10, 'Thrall'],
  [TetuGame.MONSTERS.SAVAGE_10, 'Savage'],
  [TetuGame.MONSTERS.MAGE_10, 'Mage'],
  [TetuGame.MONSTERS.ASSASSIN_10, 'Assassin'],
  [TetuGame.MONSTERS.MOCK2, 'MOCK2'],
  [TetuGame.MONSTERS.BLOODCURDLING_WOLFS_34, 'Bloodcurdling Wolfs'],
  [TetuGame.MONSTERS.SOMBER_HANGMAN_34, 'Somber Hangman'],
  [TetuGame.MONSTERS.THRALL_HUNTER_34, 'Thrall Hunter'],
  [TetuGame.MONSTERS.WILDED_ANCHORITE_34, 'Wilded Anchorite'],
  [TetuGame.MONSTERS.CHEERFUL_HANGMAN_34, 'Cheerful Hangman'],
  [TetuGame.MONSTERS.SOMBER_HANGMAN_32, 'Somber Hangman'],
  [TetuGame.MONSTERS.THRALL_HUNTER_32, 'Thrall Hunter'],
  [TetuGame.MONSTERS.WILDED_ANCHORITE_32, 'Wilded Anchorite'],
  [TetuGame.MONSTERS.CHEERFUL_HANGMAN_32, 'Cheerful Hangman'],
  [TetuGame.MONSTERS.FOREST_SHAMAN_35, 'Forest Shaman'],
  [TetuGame.MONSTERS.FILTHY_WILLY_35, 'Filthy Willy'],
  [TetuGame.MONSTERS.FOREST_SHAMAN_33, 'Forest Shaman'],
  [TetuGame.MONSTERS.FILTHY_WILLY_33, 'Filthy Willy'],
  [TetuGame.MONSTERS.RUINS_KEEPER_10, 'Ruins Keeper'],
  [TetuGame.MONSTERS.STRABAN_DOUCHEBAGS_AVENGERS_10, 'Straban Douchebags Avengers'],
  [TetuGame.MONSTERS.FUNH_3, 'Funh'],
  [TetuGame.MONSTERS.DEMOLDER_WARRIOR_34, 'Demolder Warrior'],
  [TetuGame.MONSTERS.DEMOLDER_SERGEANT_34, 'Demolder Sergeant'],
  [TetuGame.MONSTERS.DEMOLDER_BOWMAN_34, 'Demolder Bowman'],
  [TetuGame.MONSTERS.RUNE_PRIEST_34, 'Rune Priest'],
  [TetuGame.MONSTERS.DEMOLDER_HEADBRINGER_34, 'Demolder Headbringer'],
  [TetuGame.MONSTERS.ANCIENT_SERPENT_35, 'Ancient Serpent'],
  [TetuGame.MONSTERS.RUNE_KING_35, 'Rune King'],
  [TetuGame.MONSTERS.CHASER_35, 'Chaser'],
  [TetuGame.MONSTERS.A_LITTLE_MORE_BANDITS_THAN_USUAL_10, 'A Little More Bandits Than Usual'],
  [TetuGame.MONSTERS.OGRE_BARON_10, 'Ogre Baron'],
  [TetuGame.MONSTERS.ELITE_PRINCE_FELLOWS_10, 'Elite Prince Fellows'],
  [TetuGame.MONSTERS.UNFRIENDLY_HOUND_34, 'Unfriendly Hound'],
  [TetuGame.MONSTERS.BROTHER_DAMOUR_10, 'Brother Damour'],
  [TetuGame.MONSTERS.HUNGRY_BROOD_3, 'Hungry Brood'],
  [TetuGame.MONSTERS.MOCK3, 'MOCK3'],
  [TetuGame.MONSTERS.GIANT_WASP_34, 'Giant Wasp'],
  [TetuGame.MONSTERS.MOONHUNTER_34, 'Moonhunter'],
  [TetuGame.MONSTERS.GELDED_ONE_34, 'Gelded One'],
  [TetuGame.MONSTERS.RUNEBEARER_34, 'Runebearer'],
  [TetuGame.MONSTERS.DEMOLDER_BERSERK_34, 'Demolder Berserk'],
  [TetuGame.MONSTERS.SWAMP_TROLL_35, 'Swamp Troll'],
  [TetuGame.MONSTERS.INFECTED_DEADMAN_35, 'Fused Infected Deadman'],
  [TetuGame.MONSTERS.LOST_BROTHER_DAMOUR_10, 'Lost Brother Damour'],
  [TetuGame.MONSTERS.BARD_CHICK_35, 'Bard Chick'],
  [TetuGame.MONSTERS.WASP_QUEEN_35, 'Wasp Queen'],
  [TetuGame.MONSTERS.CULTIST_BOY_OF_MOTHER_34, 'Cultist Boy of Mother'],
  [TetuGame.MONSTERS.CULTIST_GIRL_OF_MOTHER_34, 'Cultist Girl of Mother'],
  [TetuGame.MONSTERS.HAKKAMANDA_10, 'Hakkamanda'],
  [TetuGame.MONSTERS.MELADZI_10, 'Meladzi'],
  [TetuGame.MONSTERS.PUG_PANIN_10, 'Pug Panin'],
  [TetuGame.MONSTERS.LEGION_COMMANDER_DOGWAN_10, 'Legion Commander Dogwan'],
  [TetuGame.MONSTERS.RUNE_KING_VISWANATHAN_10, 'Rune King Viswanathan'],
  [TetuGame.MONSTERS.GIRLS_AFTER_PARTY_35, 'Girls After Party'],
  [TetuGame.MONSTERS.MOTHER_MIOLANIA_3, 'Mother Miolania'],
  [TetuGame.MONSTERS.HANGMANS_PATROL_F2P, 'Hangmans Patrol'],
  [TetuGame.MONSTERS.A_LITTLE_MORE_BANDITS_THAN_USUAL_F2P, 'A Little More Bandits Than Usual'],
  [TetuGame.MONSTERS.REBELLIOUS_PEASANT_F2P, 'Rebellious Peasant'],
  [TetuGame.MONSTERS.DRUNK_CROSSBOWMAN_F2P, 'Drunk Crossbowman'],
  [TetuGame.MONSTERS.SOMBER_HANGMAN_F2P, 'Somber Hangman'],
  [TetuGame.MONSTERS.FILTHY_WILLY_F2P, 'Filthy Willy'],
  [TetuGame.MONSTERS.BARBARIAN_BITCH_10, 'Barbarian Bitch'],
  [TetuGame.MONSTERS.BANISHED_PEASANT_10, 'Banished Peasant'],
  [TetuGame.MONSTERS.STARVING_WOLFS_10, 'Starving Wolfs'],
  [TetuGame.MONSTERS.PEDOPHILE_HUNTER_10, 'Pedophile Hunter'],
  [TetuGame.MONSTERS.FRESH_INFECTED_DEADMAN_10, 'Fresh Infected Deadman'],
  [TetuGame.MONSTERS.STYLE_POLICE_10, 'Style Police'],
  [TetuGame.MONSTERS.BAD_BEAR_10, 'Bad Bear'],
  [TetuGame.MONSTERS.ORDINARY_GOOSE_32, 'Ordinary Goose'],
  [TetuGame.MONSTERS.ORDINARY_GOOSE_34, 'Ordinary Goose'],
  [TetuGame.MONSTERS.LOCAL_DUDE_32, 'Local Dude'],
  [TetuGame.MONSTERS.LOCAL_DUDE_34, 'Local Dude'],
  [TetuGame.MONSTERS.HUNGRY_DOG_32, 'Hungry Dog'],
  [TetuGame.MONSTERS.HUNGRY_DOG_34, 'Hungry Dog'],
  [TetuGame.MONSTERS.ROWDY_10, 'Rowdy'],
  [TetuGame.MONSTERS.OLD_WHORE_10, 'Old Whore'],
  [TetuGame.MONSTERS.TRAINING_BUDDY_33, 'Training Buddy'],
  [TetuGame.MONSTERS.FEROCIOUS_WIFE_33, 'Ferocious Wife'],
  [TetuGame.MONSTERS.FUGITIVE_KUDJA_33, 'Fugitive Kudja'],
  [TetuGame.MONSTERS.FUGITIVE_KUDJA_35, 'Fugitive Kudja'],
  [TetuGame.MONSTERS.SMELLY_CANNIBAL_34, 'Smelly Cannibal'],
  [TetuGame.MONSTERS.T_POSER_33, 'T-poser'],
  [TetuGame.MONSTERS.T_POSER_35, 'T-poser'],
  [TetuGame.MONSTERS.BAD_SEED_33, 'Bad Seed'],
  [TetuGame.MONSTERS.BAD_SEED_35, 'Bad Seed'],
  [TetuGame.MONSTERS.RIPE_MIDNIGHTER_2, 'Ripe Midnighter'],
  [TetuGame.MONSTERS.JUICY_MIDNIGHTER_2, 'Juicy Midnighter'],
  [TetuGame.MONSTERS.MERGULLIAN_HEADHUNTER_34, 'Mergullian Headhunter'],
  [TetuGame.MONSTERS.SMALL_SPIDER_34, 'Small Spider'],
  [TetuGame.MONSTERS.YOUNG_TROLL_35, 'Young Troll'],
  [TetuGame.MONSTERS.FACELESS_10, 'Faceless'],
  [TetuGame.MONSTERS.LONE_BARD_35, 'Lone Bard'],
  [TetuGame.MONSTERS.FOREST_WITCH_35, 'Forest Witch'],
  [TetuGame.MONSTERS.DARK_ADVENTURERS_35, 'Dark  Adventurers'],
  [TetuGame.MONSTERS.SPICY_MIDNIGHTER_2, 'Spicy Midnighter'],
  [TetuGame.MONSTERS.DARK_ESSENCE_35, 'Dark Essence'],
]);

const ITEMS_NAMES = new Map<string, string>([
  ['SACRA_CONS_6_ITEM', 'Dandelion Wine'],
  ['SACRA_RAGE_ITEM', 'Rage!'],
  ['SACRA_CONS_1_ITEM', 'Spoiled Berry Compote'],
  ['SACRA_OHW_9_ITEM', 'Rotten Page Sword'],
  ['SACRA_RING_2_ITEM', 'Spiked Ring'],
  ['SACRA_OFF_9_ITEM', 'Crystal Skull Orb'],
  ['SACRA_OHW_1_ITEM', 'Gaylords Rust Sword'],
  ['SACRA_CONS_20_ITEM', 'Violet Beer'],
  ['SACRA_RING_3_ITEM', 'Richly Inlaid Ring'],
  ['SACRA_SABBAH_POISON_ITEM', 'Sabbah Poison'],
  ['SACRA_STEP_BACK_ITEM', 'Step Back'],
  ['SACRA_HELM_4_ITEM', 'Deserter Helm'],
  ['SACRA_HELM_3_ITEM', 'Imperial Watchman Hood'],
  ['SACRA_REFLECTION_ITEM', 'Reflection'],
  ['SACRA_CONS_17_ITEM', 'Deer Blood'],
  ['SACRA_HEAT_STRIKE_ITEM', 'Heat Strike'],
  ['SACRA_GIANTS_BLOOD_ITEM', "Giant's Blood"],
  ['SACRA_CONS_19_ITEM', 'Sweet Poison'],
  ['SACRA_THW_7_ITEM', 'Corruptor Wand'],
  ['SACRA_OFF_6_ITEM', 'Poison Dagger'],
  ['SACRA_GLOVES_3_ITEM', 'Imperial Watchman Gloves'],
  ['SACRA_AMULET_7_ITEM', 'Deadhead'],
  ['SACRA_CONS_23_ITEM', 'Ghost Salt'],
  ['SACRA_CONS_18_ITEM', 'Sea Water'],
  ['SACRA_HELM_8_ITEM', 'Rust Deathmask'],
  ['SACRA_LAST_DANCE_ITEM', 'Last Dance'],
  ['SACRA_OHW_8_ITEM', 'Black Branch Wand'],
  ['SACRA_THW_5_ITEM', 'Cheap Myrdberg'],
  ['SACRA_CONS_2_ITEM', 'Spider Juice'],
  ['SACRA_JUSTICE_ITEM', 'Justice'],
  ['SACRA_GUIDING_LIGHT_ITEM', 'Guiding Light'],
  ['SACRA_TIME_AND_EXPERIENCE_ITEM', 'Time and Experience'],
  ['SACRA_BODY_3_ITEM', 'Imperial Watchman Armor'],
  ['SACRA_BEEF_PATTY_ITEM', 'Beef Patty'],
  ['SACRA_OFF_7_ITEM', 'Northtribe Shield'],
  ['SACRA_AMULET_11_ITEM', 'Flower of Champions'],
  ['SACRA_THW_3_ITEM', 'Ritual Hummer'],
  ['SACRA_ICE_SHARD_ITEM', 'Ice Shard'],
  ['SACRA_OFF_11_ITEM', 'Isaacs Nigidium'],
  ['SACRA_BODY_2_ITEM', 'Caitiff Jacket'],
  ['SACRA_I_SURVIVE_ITEM', "I'm Survive"],
  ['SACRA_GLOVES_8_ITEM', 'Rust Deathclaws'],
  ['SACRA_BODY_5_ITEM', 'Rust Heavy Plate'],
  ['SACRA_AMULET_6_ITEM', 'Demon Sign'],
  ['SACRA_CONS_10_ITEM', 'Blue Lagoon'],
  ['SACRA_AMULET_10_ITEM', 'Lucky Deer Horn'],
  ['SACRA_SPIT_IN_FACE_ITEM', 'Spit in Face'],
  ['SACRA_GUT_PUNCH_ITEM', 'Gut Punch!'],
  ['SACRA_OHW_4_ITEM', 'Bandit Axe'],
  ['SACRA_BELT_4_ITEM', "Officer's Belt"],
  ['SACRA_THW_4_ITEM', 'Great Northbye'],
  ['SACRA_RING_9_ITEM', 'Madmans Ring'],
  ['SACRA_RING_7_ITEM', "Garold's Ring"],
  ['SACRA_CONS_22_ITEM', 'Demon Seal'],
  ['SACRA_BODY_4_ITEM', 'Deserter Armor'],
  ['SACRA_HELM_5_ITEM', "Jagga's Cauldron"],
  ['SACRA_HELM_7_ITEM', 'Pirate Helmet'],
  ['SACRA_GLOVES_6_ITEM', 'Slaughterers Bracelets'],
  ['SACRA_MELT_ITEM', 'Melt'],
  ['SACRA_CONS_11_ITEM', 'Bumpkin Absinthe'],
  ['SACRA_CONS_21_ITEM', 'Chicken Thigh with Rosemary'],
  ['SACRA_THW_11_ITEM', 'Dawn Box'],
  ['SACRA_OHW_13_ITEM', 'Elegant Hammer'],
  ['SACRA_FEAR_ITEM', 'Fear'],
  ['SACRA_SCARLET_BRANCH_ADEPT_ITEM', 'Scarlet Branch Adept'],
  ['SACRA_PATIENCE_ITEM', 'Patience'],
  ['SACRA_OHW_12_ITEM', 'Prince Hobnail'],
  ['SACRA_CONS_12_ITEM', 'Snake Milkshake'],
  ['SACRA_CONS_9_ITEM', 'Fruit Tea'],
  ['SACRA_BOOTS_6_ITEM', 'Swamp Knight Boots'],
  ['SACRA_BOOTS_1_ITEM', 'Dumb Bandit Sandals'],
  ['SACRA_RING_4_ITEM', 'Hunter Ring'],
  ['SACRA_GLOVES_7_ITEM', 'Page Gloves'],
  ['SACRA_RING_10_ITEM', 'Serpent Skin'],
  ['SACRA_RING_8_ITEM', "Ancient Mage's Ring"],
  ['SACRA_HELM_6_ITEM', 'Witch Blindfold'],
  ['SACRA_OHW_2_ITEM', 'Rusty Cleaver'],
  ['SACRA_CONS_26_ITEM', 'Old Map'],
  ['SACRA_CONS_3_ITEM', 'Dose of Spinach'],
  ['SACRA_RING_1_ITEM', 'Wooden Ring'],
  ['SACRA_LIFEDRAIN_ITEM', 'Lifedrain'],
  ['SACRA_OFF_1_ITEM', 'Middle Finger'],
  ['SACRA_OHW_14_ITEM', 'Old Depilatorium'],
  ['SACRA_BOOTS_3_ITEM', 'Imperial Watchman Boots'],
  ['SACRA_THW_2_ITEM', 'Crap Iron Spear'],
  ['SACRA_AMULET_5_ITEM', 'Highlander Talisman'],
  ['SACRA_ANATHEMA_ITEM', 'Anathema'],
  ['SACRA_SAVAGE_CHARM_ITEM', 'Savage Charm!'],
  ['SACRA_AMULET_1_ITEM', 'Witchhand'],
  ['SACRA_AMULET_12_ITEM', 'Faded Pendant'],
  ['SACRA_ONSLAUGHT_ITEM', 'Onslaught'],
  ['SACRA_ARMOR_OF_FAITH_ITEM', 'Armor of Faith'],
  ['SACRA_BACKSTAB_ITEM', 'Backstab'],
  ['SACRA_CONS_14_ITEM', 'Octopus Blood'],
  ['SACRA_LIVE_FORTRESS_ITEM', 'Live Fortress'],
  ['SACRA_OFF_8_ITEM', 'Parry Dagger'],
  ['SACRA_CONS_15_ITEM', 'Horsecock Extract'],
  ['SACRA_STRONG_BLOCK_ITEM', 'Strong Block'],
  ['SACRA_GLOVES_5_ITEM', 'Assasin Graceful Bracelets'],
  ['SACRA_OFF_13_ITEM', 'Key to Nothing'],
  ['SACRA_ERASE_ITEM', 'Erase'],
  ['SACRA_GLOVES_4_ITEM', 'Deserter Gauntlets'],
  ['SACRA_BODY_1_ITEM', 'Dumb Bandit Swimsuit'],
  ['SACRA_BOOTS_4_ITEM', 'Deserter Greaves'],
  ['SACRA_CONS_5_ITEM', 'Good Berry Compote'],
  ['SACRA_GOLDEN_EYE_ITEM', 'Golden Eye'],
  ['SACRA_CONS_24_ITEM', 'Protective Decree'],
  ['SACRA_BRUTE_FORCE_ITEM', 'Brute Force'],
  ['SACRA_COLD_SHOULDER_ITEM', 'Cold Shoulder'],
  ['SACRA_CONS_8_ITEM', 'Eggplant Moonshine'],
  ['SACRA_OFF_10_ITEM', 'Big Pretty Fish'],
  ['SACRA_DEMON_SPEED_ITEM', 'Demon Speed'],
  ['SACRA_AMULET_4_ITEM', 'Security Talisman'],
  ['SACRA_OFF_2_ITEM', 'Creepy Idol'],
  ['SACRA_AMULET_9_ITEM', 'Old Symbol of Power'],
  ['SACRA_DEAD_STRIKE_ITEM', 'Dead Strike'],
  ['SACRA_AMULET_8_ITEM', 'Black Branch Amulet'],
  ['SACRA_AMULET_2_ITEM', 'Strange Rock'],
  ['SACRA_FIRM_HAND_ITEM', 'Firm Hand'],
  ['SACRA_BODY_7_ITEM', 'Human Skin Gown'],
  ['SACRA_HELM_1_ITEM', 'Bandit Crap Hat'],
  ['SACRA_THW_6_ITEM', 'Chief Axe'],
  ['SACRA_HELM_2_ITEM', 'Caitiff Hood'],
  ['SACRA_OHW_3_ITEM', 'Blind Mage Fence Part'],
  ['SACRA_OFF_3_ITEM', 'Teardrop Shield'],
  ['SACRA_CONS_25_ITEM', 'Cadaveric Honey'],
  ['SACRA_THUNDERBOLT_ITEM', 'Thunderbolt'],
  ['SACRA_OHW_5_ITEM', 'Scoundrels Dagger'],
  ['SACRA_BELT_1_ITEM', 'Piece of Deer Intestine'],
  ['SACRA_OFF_4_ITEM', 'Evil Deads Nigidium'],
  ['SACRA_AMULET_3_ITEM', 'Bravery Medal'],
  ['SACRA_STATIC_DISCHARGE_ITEM', 'Static Discharge'],
  ['SACRA_OFF_12_ITEM', 'Broken Key'],
  ['SACRA_VETERAN_CONFIDENCE_ITEM', 'Veteran Confidence'],
  ['SACRA_THW_10_ITEM', 'The Fencers Arguments'],
  ['SACRA_CONS_4_ITEM', 'Portion of Oatmeal'],
  ['SACRA_GLOVES_2_ITEM', 'Caitiff Gloves'],
  ['SACRA_CONS_7_ITEM', 'Cucumber Smoothie'],
  ['SACRA_RING_6_ITEM', 'Golden Plaque'],
  ['SACRA_THW_9_ITEM', 'Heavy Crossbow'],
  ['SACRA_BELT_3_ITEM', 'Street Dancer Belt'],
  ['SACRA_OHW_10_ITEM', 'Deviant Wand'],
  ['SACRA_BOOTS_5_ITEM', 'Fishing Boots'],
  ['SACRA_BOOTS_2_ITEM', 'Caitiff Boots'],
  ['SACRA_BELT_2_ITEM', 'Crappy Leather Belt'],
  ['SACRA_PARALYZE_ITEM', 'Paralyze'],
  ['SACRA_THW_8_ITEM', 'Infantry Bihander'],
  ['SACRA_BODY_6_ITEM', 'Interrogators Cloak'],
  ['SACRA_BOOTS_7_ITEM', 'Rust Deathboots'],
  ['SACRA_CONS_13_ITEM', 'Cherry Rom'],
  ['SACRA_OHW_11_ITEM', 'Solid Mace'],
  ['SACRA_FROSTBITE_ITEM', 'Frostbite'],
  ['SACRA_THW_1_ITEM', 'Wooden Skullcrusher'],
  ['SACRA_OHW_7_ITEM', 'Mergull Spata'],
  ['SACRA_OHW_6_ITEM', 'Imperial Scimitar'],
  ['SACRA_CONS_16_ITEM', "Old Lady's Sweat "],
  ['SACRA_LIKE_A_PUSSY_ITEM', 'Like a pussy!'],
  ['SACRA_OFF_5_ITEM', 'Fencer Buckler '],
  ['SACRA_STEEL_SKIN_ITEM', 'Steel Skin'],
  ['SACRA_GLOVES_1_ITEM', 'Dumb Bandit Mittens'],
  ['SACRA_RING_5_ITEM', 'Braided Serpent'],
  ['SACRA_CONS_27_ITEM', 'Burdock Leaf'],
  ['SACRA_CONS_28_ITEM', 'Pink Vine'],
  ['SACRA_CONS_29_ITEM', 'Dull Blood Tear'],
  ['SACRA_CONS_30_ITEM', 'Feeble Blood Tear'],
  ['SACRA_CONS_31_ITEM', 'Sharp Blood Tear'],
  ['SACRA_CONS_32_ITEM', 'Saturated Blood Tear'],
  ['SACRA_CONS_33_ITEM', "Watchman's Crystal Whistle"],
  ['SACRA_CONS_34_ITEM', 'Sacra Tree Twig'],
  ['SACRA_CONS_35_ITEM', 'Blessed Water'],
  ['SACRA_HELM_9_ITEM', 'Bone Glasses'],
  ['SACRA_BELT_5_ITEM', 'Ass Spanking Belt'],
  ['SACRA_AMULET_13_ITEM', 'Fancy Potato'],
  ['SACRA_BODY_8_ITEM', 'Nipple Piercing'],
  ['SACRA_RING_11_ITEM', 'Ice Song'],
]);

export function getItemNameBySymbol(itemSymbol: string): string {
  return ITEMS_NAMES.get(itemSymbol) || itemSymbol;
}
