import { TetuGame } from './TetuGame';

export function getMonsterName(monsterId: number): string {
  const name = MONSTER_NAMES.get(monsterId);
  if (!name) {
    console.log(`No name found for ${monsterId}`);
    return 'Unknown';
  }
  return name;
}

export const MONSTER_NAMES = new Map<number, string>([
  [TetuGame.MONSTERS.REBELLIOUS_PEASANT_32, 'Rebellious Peasant'],
  [TetuGame.MONSTERS.REBELLIOUS_PEASANT_34, 'Rebellious Peasant'],
  [TetuGame.MONSTERS.TOUGH_DESERTER_32, 'Tough Deserter'],
  [TetuGame.MONSTERS.TOUGH_DESERTER_34, 'Tough Deserter'],
  [TetuGame.MONSTERS.BLOODTHIRSTY_MADMAN_32, 'Bloodthirsty Madman'],
  [TetuGame.MONSTERS.BLOODTHIRSTY_MADMAN_34, 'Bloodthirsty Madman'],
  [TetuGame.MONSTERS.FEROCIOUS_WOLFS_34, 'Ferocious Wolfs'],
  [TetuGame.MONSTERS.DRUNK_CROSSBOWMAN_32, 'Drunk Crossbowman'],
  [TetuGame.MONSTERS.DRUNK_CROSSBOWMAN_34, 'Drunk Crossbowman'],
  [TetuGame.MONSTERS.VILE_SERPENT_35, 'Vile Serpent'],
  [TetuGame.MONSTERS.THE_MAN_EATING_BEAR_35, 'The Man-Eating Bear'],
  [TetuGame.MONSTERS.BANDIT_CROWD_10, 'Bandit Crowd'],
  [TetuGame.MONSTERS.HANGMANS_PATROL_33, 'Hangmans Patrol'],
  [TetuGame.MONSTERS.MIDNIGHTER_2, 'Midnighter'],
  [TetuGame.MONSTERS.FOREST_CHORT_35, 'Forest Chort'],
  [TetuGame.MONSTERS.INFECTED_SPIRIT_OF_THE_FOREST_3, 'Infected Spirit of the Forest'],
  [TetuGame.MONSTERS.RESTLESS_SPIRIT_10, 'Restless Spirit'],
  [TetuGame.MONSTERS.MOCK1, 'MOCK1'],
  [TetuGame.MONSTERS.INFECTED_DEADMAN_JUNIOR_32, 'Infected Deadman'],
  [TetuGame.MONSTERS.INFECTED_DEADMAN_JUNIOR_34, 'Infected Deadman'],
  [TetuGame.MONSTERS.THRALL_10, 'Thrall'],
  [TetuGame.MONSTERS.SAVAGE_10, 'Savage'],
  [TetuGame.MONSTERS.MAGE_10, 'Mage'],
  [TetuGame.MONSTERS.ASSASSIN_10, 'Assassin'],
  [TetuGame.MONSTERS.MOCK2, 'MOCK2'],
  [TetuGame.MONSTERS.BLOODCURDLING_WOLFS_34, 'Bloodcurdling Wolfs'],
  [TetuGame.MONSTERS.SOMBER_HANGMAN_34, 'Somber Hangman'],
  [TetuGame.MONSTERS.THRALL_HUNTER_34, 'Thrall Hunter'],
  [TetuGame.MONSTERS.WILDED_ANCHORITE_34, 'Wilded Anchorite'],
  [TetuGame.MONSTERS.CHEERFUL_HANGMAN_34, 'Cheerful Hangman'],
  [TetuGame.MONSTERS.SOMBER_HANGMAN_32, 'Somber Hangman'],
  [TetuGame.MONSTERS.THRALL_HUNTER_32, 'Thrall Hunter'],
  [TetuGame.MONSTERS.WILDED_ANCHORITE_32, 'Wilded Anchorite'],
  [TetuGame.MONSTERS.CHEERFUL_HANGMAN_32, 'Cheerful Hangman'],
  [TetuGame.MONSTERS.FOREST_SHAMAN_35, 'Forest Shaman'],
  [TetuGame.MONSTERS.FILTHY_WILLY_35, 'Filthy Willy'],
  [TetuGame.MONSTERS.FOREST_SHAMAN_33, 'Forest Shaman'],
  [TetuGame.MONSTERS.FILTHY_WILLY_33, 'Filthy Willy'],
  [TetuGame.MONSTERS.RUINS_KEEPER_10, 'Ruins Keeper'],
  [TetuGame.MONSTERS.STRABAN_DOUCHEBAGS_AVENGERS_10, 'Straban Douchebags Avengers'],
  [TetuGame.MONSTERS.FUNH_3, 'Funh'],
  [TetuGame.MONSTERS.DEMOLDER_WARRIOR_34, 'Demolder Warrior'],
  [TetuGame.MONSTERS.DEMOLDER_SERGEANT_34, 'Demolder Sergeant'],
  [TetuGame.MONSTERS.DEMOLDER_BOWMAN_34, 'Demolder Bowman'],
  [TetuGame.MONSTERS.RUNE_PRIEST_34, 'Rune Priest'],
  [TetuGame.MONSTERS.DEMOLDER_HEADBRINGER_34, 'Demolder Headbringer'],
  [TetuGame.MONSTERS.ANCIENT_SERPENT_35, 'Ancient Serpent'],
  [TetuGame.MONSTERS.RUNE_KING_35, 'Rune King'],
  [TetuGame.MONSTERS.CHASER_35, 'Chaser'],
  [TetuGame.MONSTERS.A_LITTLE_MORE_BANDITS_THAN_USUAL_10, 'A Little More Bandits Than Usual'],
  [TetuGame.MONSTERS.OGRE_BARON_10, 'Ogre Baron'],
  [TetuGame.MONSTERS.ELITE_PRINCE_FELLOWS_10, 'Elite Prince Fellows'],
  [TetuGame.MONSTERS.UNFRIENDLY_HOUND_34, 'Unfriendly Hound'],
  [TetuGame.MONSTERS.BROTHER_DAMOUR_10, 'Brother Damour'],
  [TetuGame.MONSTERS.HUNGRY_BROOD_3, 'Hungry Brood'],
  [TetuGame.MONSTERS.MOCK3, 'MOCK3'],
  [TetuGame.MONSTERS.GIANT_WASP_34, 'Giant Wasp'],
  [TetuGame.MONSTERS.MOONHUNTER_34, 'Moonhunter'],
  [TetuGame.MONSTERS.GELDED_ONE_34, 'Gelded One'],
  [TetuGame.MONSTERS.RUNEBEARER_34, 'Runebearer'],
  [TetuGame.MONSTERS.DEMOLDER_BERSERK_34, 'Demolder Berserk'],
  [TetuGame.MONSTERS.SWAMP_TROLL_35, 'Swamp Troll'],
  [TetuGame.MONSTERS.INFECTED_DEADMAN_35, 'Fused Infected Deadman'],
  [TetuGame.MONSTERS.LOST_BROTHER_DAMOUR_10, 'Lost Brother Damour'],
  [TetuGame.MONSTERS.BARD_CHICK_35, 'Bard Chick'],
  [TetuGame.MONSTERS.WASP_QUEEN_35, 'Wasp Queen'],
  [TetuGame.MONSTERS.CULTIST_BOY_OF_MOTHER_34, 'Cultist Boy of Mother'],
  [TetuGame.MONSTERS.CULTIST_GIRL_OF_MOTHER_34, 'Cultist Girl of Mother'],
  [TetuGame.MONSTERS.HAKKAMANDA_10, 'Hakkamanda'],
  [TetuGame.MONSTERS.MELADZI_10, 'Meladzi'],
  [TetuGame.MONSTERS.PUG_PANIN_10, 'Pug Panin'],
  [TetuGame.MONSTERS.LEGION_COMMANDER_DOGWAN_10, 'Legion Commander Dogwan'],
  [TetuGame.MONSTERS.RUNE_KING_VISWANATHAN_10, 'Rune King Viswanathan'],
  [TetuGame.MONSTERS.GIRLS_AFTER_PARTY_35, 'Girls After Party'],
  [TetuGame.MONSTERS.MOTHER_MIOLANIA_3, 'Mother Miolania'],
  [TetuGame.MONSTERS.HANGMANS_PATROL_F2P, 'Hangmans Patrol'],
  [TetuGame.MONSTERS.A_LITTLE_MORE_BANDITS_THAN_USUAL_F2P, 'A Little More Bandits Than Usual'],
  [TetuGame.MONSTERS.REBELLIOUS_PEASANT_F2P, 'Rebellious Peasant'],
  [TetuGame.MONSTERS.DRUNK_CROSSBOWMAN_F2P, 'Drunk Crossbowman'],
  [TetuGame.MONSTERS.SOMBER_HANGMAN_F2P, 'Somber Hangman'],
  [TetuGame.MONSTERS.FILTHY_WILLY_F2P, 'Filthy Willy'],
  [TetuGame.MONSTERS.BARBARIAN_BITCH_10, 'Barbarian Bitch'],
  [TetuGame.MONSTERS.BANISHED_PEASANT_10, 'Banished Peasant'],
  [TetuGame.MONSTERS.STARVING_WOLFS_10, 'Starving Wolfs'],
  [TetuGame.MONSTERS.PEDOPHILE_HUNTER_10, 'Pedophile Hunter'],
  [TetuGame.MONSTERS.FRESH_INFECTED_DEADMAN_10, 'Fresh Infected Deadman'],
  [TetuGame.MONSTERS.STYLE_POLICE_10, 'Style Police'],
  [TetuGame.MONSTERS.BAD_BEAR_10, 'Bad Bear'],
  [TetuGame.MONSTERS.ORDINARY_GOOSE_32, 'Ordinary Goose'],
  [TetuGame.MONSTERS.ORDINARY_GOOSE_34, 'Ordinary Goose'],
  [TetuGame.MONSTERS.LOCAL_DUDE_32, 'Local Dude'],
  [TetuGame.MONSTERS.LOCAL_DUDE_34, 'Local Dude'],
  [TetuGame.MONSTERS.HUNGRY_DOG_32, 'Hungry Dog'],
  [TetuGame.MONSTERS.HUNGRY_DOG_34, 'Hungry Dog'],
  [TetuGame.MONSTERS.ROWDY_10, 'Rowdy'],
  [TetuGame.MONSTERS.OLD_WHORE_10, 'Old Whore'],
  [TetuGame.MONSTERS.TRAINING_BUDDY_33, 'Training Buddy'],
  [TetuGame.MONSTERS.FEROCIOUS_WIFE_33, 'Ferocious Wife'],
  [TetuGame.MONSTERS.FUGITIVE_KUDJA_33, 'Fugitive Kudja'],
  [TetuGame.MONSTERS.FUGITIVE_KUDJA_35, 'Fugitive Kudja'],
  [TetuGame.MONSTERS.SMELLY_CANNIBAL_34, 'Smelly Cannibal'],
  [TetuGame.MONSTERS.T_POSER_33, 'T-poser'],
  [TetuGame.MONSTERS.T_POSER_35, 'T-poser'],
  [TetuGame.MONSTERS.BAD_SEED_33, 'Bad Seed'],
  [TetuGame.MONSTERS.BAD_SEED_35, 'Bad Seed'],
  [TetuGame.MONSTERS.RIPE_MIDNIGHTER_2, 'Ripe Midnighter'],
  [TetuGame.MONSTERS.JUICY_MIDNIGHTER_2, 'Juicy Midnighter'],
  [TetuGame.MONSTERS.MERGULLIAN_HEADHUNTER_34, 'Mergullian Headhunter'],
  [TetuGame.MONSTERS.SMALL_SPIDER_34, 'Small Spider'],
  [TetuGame.MONSTERS.YOUNG_TROLL_35, 'Young Troll'],
  [TetuGame.MONSTERS.FACELESS_10, 'Faceless'],
  [TetuGame.MONSTERS.LONE_BARD_35, 'Lone Bard'],
  [TetuGame.MONSTERS.FOREST_WITCH_35, 'Forest Witch'],
  [TetuGame.MONSTERS.DARK_ADVENTURERS_35, 'Dark  Adventurers'],
  [TetuGame.MONSTERS.SPICY_MIDNIGHTER_2, 'Spicy Midnighter'],
  [TetuGame.MONSTERS.DARK_ESSENCE_35, 'Dark Essence'],
]);
