import { MENU_ITEMS } from './menu.constant';


export const MAIN_ROUTES = {
  [MENU_ITEMS.USER_STAT]: 'user-stat',
  [MENU_ITEMS.HERO_STAT]: 'hero-stat',
  [MENU_ITEMS.ITEM_STAT]: 'item-stat',
  [MENU_ITEMS.NEW_USERS]: 'new-users',
  [MENU_ITEMS.USERS_REF]: 'users-ref',
  [MENU_ITEMS.USER_GENERAL_STAT]: 'user-general-stat',
  [MENU_ITEMS.NEW_HEROES]: 'new-heroes',
  [MENU_ITEMS.STORY_STAT]: 'story-stat',
  [MENU_ITEMS.TOKENOMICS]: 'tokenomics',
  [MENU_ITEMS.TOKENOMICS_CHART]: 'tokenomics-stat',
  [MENU_ITEMS.TOKENS_TRANSACTIONS]: 'token-transactions',
  [MENU_ITEMS.MONSTER_FIGHTS]: 'monster-fights',
  [MENU_ITEMS.HERO_FIGHTS]: 'hero-fights',
  [MENU_ITEMS.PAWNSHOP_CHART]: 'pawnshop-chart',
  [MENU_ITEMS.DAU_CHART]: 'dau-chart',
  [MENU_ITEMS.EARNED_BY_BIOME]: 'earned-by-biome',
  [MENU_ITEMS.TX_CHART]: 'tx-chart',
  [MENU_ITEMS.USERS_RATIO_EARN]: 'users-ratio-earn',
  [MENU_ITEMS.CHURN_RATE]: 'churn-rate',
  [MENU_ITEMS.CHURN_RATE_V2]: 'churn-rate-v2',
  [MENU_ITEMS.TOTAL_SUPPLY]: 'total-supply',
  [MENU_ITEMS.PAWNSHOP_STAT_CHART]: 'pawnshop-stat-chart',
  [MENU_ITEMS.PAWNSHOP_PRICE_RANGE]: 'pawnshop-price-range',
  [MENU_ITEMS.TABLE_ITEM_GENERAL_STAT]: 'table-item-general-stat',
  [MENU_ITEMS.TABLE_ITEM_MINT_IN_STORY_STAT]: 'table-item-min-in-story-stat',
  [MENU_ITEMS.TABLE_STORY_PAGE_NOT_PASSED]: 'table-story-page-not-passed',
  [MENU_ITEMS.REINFORCEMENT_V2]: 'reinforcement-v2',
};